name: fossil-fuel-matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask=3.0.0
  - pandas=2.1.4
  - pip
  - pip:
    - fuzzywuzzy==0.18.0
    - python-Levenshtein==0.25.0
